Issue-79 Added contextual targeting support
taboola/backstage-api-java-client pull request #80
Opened 2023-12-07 13:09 UTC by gldiazcardenas

https://github.com/taboola/backstage-api-java-client/issues/79

Endpoints:

- Read Contextual Segments
- Read Contextual Segments by Country
- Update Contextual Segment Targeting
- Read Contextual Segment Targeting

2023-12-07 21:56 UTC, vladimanaev commented on src/main/java/com/taboola/backstage/model/dictionary/ContextualSegment.java
> + * Copyright 2023 InPowered. All Rights Reserved.
Please remove Copyright header

2023-12-07 22:07 UTC, vladimanaev commented on src/main/java/com/taboola/backstage/model/dictionary/ContextualSegment.java
> +public class ContextualSegment {
Please impl toString method

2023-12-07 22:10 UTC, vladimanaev requested changes
- Missing toString method on class ContextualSegment
- Copyright header should be removed from class ContextualSegment

Everything else seem good.

2023-12-11 13:09 UTC, gldiazcardenas commented
Changes done

2023-12-11 21:48 UTC, vladimanaev approved these changes

2023-12-11 21:49 UTC, merged